import json

# -----------------------------
# INDUSTRIES (Google My Business categories) - Massively Expanded & Global
# -----------------------------
industries = [
    # --- Manufacturing & Industrial ---
    {"key": "manufacturing", "query": "Manufacturing company"},
    {"key": "factory", "query": "Factory"},
    {"key": "textile", "query": "Textile company"},
    {"key": "garment", "query": "Garment industry"},
    {"key": "mining", "query": "Mining company"},
    {"key": "quarry", "query": "Quarry"},
    {"key": "energy", "query": "Energy company"},
    {"key": "solar", "query": "Solar energy company"},
    {"key": "wind_farm", "query": "Wind farm"},
    {"key": "oil_and_gas", "query": "Oil and gas company"},
    {"key": "agriculture", "query": "Agriculture company"},
    {"key": "dairy", "query": "Dairy industry"},
    {"key": "poultry_farm", "query": "Poultry farm"},
    {"key": "fish_farm", "query": "Fish farm"},
    {"key": "agrovet", "query": "Agro vet"},
    {"key": "farm_supply", "query": "Farm supply store"},
    {"key": "food_processing", "query": "Food processing industry"},
    {"key": "beverage_company", "query": "Beverage company"},
    {"key": "plastic_industry", "query": "Plastic industry"},
    {"key": "paper_industry", "query": "Paper industry"},
    {"key": "chemical_industry", "query": "Chemical company"},
    {"key": "pharmaceutical_manufacturer", "query": "Pharmaceutical manufacturer"},
    {"key": "steel_industry", "query": "Steel industry"},
    {"key": "metal_fabrication", "query": "Metal fabrication"},
    {"key": "cement", "query": "Cement company"},
    {"key": "brick_kiln", "query": "Brick kiln"},
    {"key": "glass_industry", "query": "Glass manufacturer"},
    {"key": "rubber_industry", "query": "Rubber manufacturer"},
    {"key": "machinery_manufacturer", "query": "Machinery manufacturer"},
    {"key": "packaging_company", "query": "Packaging company"},
    {"key": "bottling_plant", "query": "Bottling plant"},
    {"key": "wood_industry", "query": "Sawmill"},
    {"key": "furniture_manufacturer", "query": "Furniture manufacturer"},
    {"key": "electronics_manufacturer", "query": "Electronics manufacturer"},
    {"key": "printing_press", "query": "Printing press"},

    # --- Automotive ---
    {"key": "automobile_showroom", "query": "Car dealership"},
    {"key": "used_car_dealer", "query": "Used car dealer"},
    {"key": "car_dealer", "query": "Car dealer"},
    {"key": "bike_dealer", "query": "Motorcycle dealer"},
    {"key": "atv_dealer", "query": "ATV dealer"},
    {"key": "boat_dealer", "query": "Boat dealer"},
    {"key": "rv_dealer", "query": "RV dealer"},
    {"key": "vehicle_workshop", "query": "Auto repair shop"},
    {"key": "car_repair", "query": "Car repair shop"},
    {"key": "bike_repair", "query": "Motorcycle repair shop"},
    {"key": "auto_glass", "query": "Auto glass shop"},
    {"key": "car_wash", "query": "Car wash"},
    {"key": "auto_detailing", "query": "Auto detailing"},
    {"key": "gas_station", "query": "Gas station"},
    {"key": "fuel_station", "query": "Fuel station"},
    {"key": "ev_charging_station", "query": "EV charging station"},
    {"key": "tire_shop", "query": "Tire shop"},
    {"key": "spare_parts", "query": "Spare parts shop"},
    {"key": "auto_parts_store", "query": "Auto parts store"},
    {"key": "car_battery_shop", "query": "Car battery shop"},
    {"key": "muffler_shop", "query": "Muffler shop"},
    {"key": "transmission_shop", "query": "Transmission shop"},
    {"key": "towing_service", "query": "Towing service"},
    {"key": "car_rental", "query": "Car rental"},
    {"key": "taxi_service", "query": "Taxi service"},
    {"key": "limousine_service", "query": "Limousine service"},
    {"key": "driving_school", "query": "Driving school"},
    {"key": "traffic_school", "query": "Traffic school"},
    {"key": "parking_lot", "query": "Parking lot"},

    # --- Health & Wellness ---
    {"key": "hospital", "query": "Hospital"},
    {"key": "clinic", "query": "Medical clinic"},
    {"key": "urgent_care", "query": "Urgent care center"},
    {"key": "pharmacy", "query": "Pharmacy"},
    {"key": "drugstore", "query": "Drugstore"},
    {"key": "dental_clinic", "query": "Dental clinic"},
    {"key": "dentist", "query": "Dentist"},
    {"key": "orthodontist", "query": "Orthodontist"},
    {"key": "endodontist", "query": "Endodontist"},
    {"key": "periodontist", "query": "Periodontist"},
    {"key": "eye_care", "query": "Eye care center"},
    {"key": "optician", "query": "Optician"},
    {"key": "ophthalmologist", "query": "Ophthalmologist"},
    {"key": "physiotherapy", "query": "Physiotherapist"},
    {"key": "chiropractor", "query": "Chiropractor"},
    {"key": "podiatrist", "query": "Podiatrist"},
    {"key": "mental_health_clinic", "query": "Mental health clinic"},
    {"key": "psychiatrist", "query": "Psychiatrist"},
    {"key": "psychologist", "query": "Psychologist"},
    {"key": "addiction_treatment", "query": "Addiction treatment center"},
    {"key": "rehab_center", "query": "Rehabilitation center"},
    {"key": "pathology_lab", "query": "Pathology lab"},
    {"key": "diagnostic_center", "query": "Diagnostic center"},
    {"key": "x_ray_lab", "query": "X-ray lab"},
    {"key": "mri_center", "query": "MRI center"},
    {"key": "blood_bank", "query": "Blood bank"},
    {"key": "medical_store", "query": "Medical store"},
    {"key": "medical_supplies", "query": "Medical supplies"},
    {"key": "hospital_equipment", "query": "Hospital equipment supplier"},
    {"key": "nursing_home", "query": "Nursing home"},
    {"key": "assisted_living", "query": "Assisted living facility"},
    {"key": "hospice", "query": "Hospice"},
    {"key": "gym", "query": "Gym"},
    {"key": "fitness_center", "query": "Fitness center"},
    {"key": "yoga_studio", "query": "Yoga studio"},
    {"key": "pilates_studio", "query": "Pilates studio"},
    {"key": "crossfit_box", "query": "Crossfit box"},
    {"key": "martial_arts_school", "query": "Martial arts school"},
    {"key": "personal_trainer", "query": "Personal trainer"},
    {"key": "nutritionist", "query": "Nutritionist"},
    {"key": "dietitian", "query": "Dietitian"},
    {"key": "spa_wellness", "query": "Day spa"},
    {"key": "massage_therapist", "query": "Massage therapist"},
    {"key": "acupuncture", "query": "Acupuncture clinic"},
    {"key": "beauty_salon", "query": "Beauty salon"},
    {"key": "hair_salon", "query": "Hair salon"},
    {"key": "nail_salon", "query": "Nail salon"},
    {"key": "barber_shop", "query": "Barber shop"},
    {"key": "parlor", "query": "Beauty parlor"},
    {"key": "skin_care_clinic", "query": "Skin care clinic"},
    {"key": "dermatologist", "query": "Dermatologist"},
    {"key": "laser_center", "query": "Laser hair removal"},
    {"key": "tattoo_shop", "query": "Tattoo shop"},
    {"key": "tattoo_removal", "query": "Tattoo removal"},
    {"key": "piercing_shop", "query": "Piercing shop"},
    {"key": "hair_removal", "query": "Hair removal service"},
    {"key": "veterinary", "query": "Veterinarian"},
    {"key": "animal_hospital", "query": "Animal hospital"},
    {"key": "pet_store", "query": "Pet store"},
    {"key": "pet_groomer", "query": "Pet groomer"},
    {"key": "kennel", "query": "Kennel"},
    {"key": "dog_walker", "query": "Dog walker"},
    {"key": "pet_sitter", "query": "Pet sitter"},

    # --- Education ---
    {"key": "school", "query": "School"},
    {"key": "high_school", "query": "High school"},
    {"key": "middle_school", "query": "Middle school"},
    {"key": "elementary_school", "query": "Elementary school"},
    {"key": "charter_school", "query": "Charter school"},
    {"key": "college", "query": "College"},
    {"key": "university", "query": "University"},
    {"key": "community_college", "query": "Community college"},
    {"key": "training_institute", "query": "Training institute"},
    {"key": "vocational_school", "query": "Vocational school"},
    {"key": "trade_school", "query": "Trade school"},
    {"key": "education_consultancy", "query": "Education consultancy"},
    {"key": "study_abroad_agency", "query": "Study abroad agency"},
    {"key": "computer_institute", "query": "Computer institute"},
    {"key": "language_class", "query": "Language school"},
    {"key": "english_school", "query": "English language school"},
    {"key": "tuition_center", "query": "Tuition center"},
    {"key": "tutoring_service", "query": "Tutoring service"},
    {"key": "library", "query": "Library"},
    {"key": "montessori", "query": "Montessori school"},
    {"key": "daycare", "query": "Daycare center"},
    {"key": "preschool", "query": "Preschool"},
    {"key": "kindergarten", "query": "Kindergarten"},
    {"key": "art_school", "query": "Art school"},
    {"key": "music_school", "query": "Music school"},
    {"key": "dance_school", "query": "Dance school"},
    {"key": "cooking_class", "query": "Cooking class"},
    {"key": "swimming_school", "query": "Swimming school"},

    # --- Real Estate & Construction ---
    {"key": "realestate", "query": "Real estate agency"},
    {"key": "realestate_agent", "query": "Real estate agent"},
    {"key": "realtor", "query": "Realtor"},
    {"key": "commercial_realestate", "query": "Commercial real estate"},
    {"key": "property_management", "query": "Property management"},
    {"key": "apartment_building", "query": "Apartment complex"},
    {"key": "construction_company", "query": "Construction company"},
    {"key": "general_contractor", "query": "General contractor"},
    {"key": "home_builder", "query": "Home builder"},
    {"key": "custom_builder", "query": "Custom home builder"},
    {"key": "civil_engineer", "query": "Civil engineer"},
    {"key": "structural_engineer", "query": "Structural engineer"},
    {"key": "architect", "query": "Architect"},
    {"key": "landscape_architect", "query": "Landscape architect"},
    {"key": "interior_design", "query": "Interior designer"},
    {"key": "home_inspector", "query": "Home inspector"},
    {"key": "surveyor", "query": "Land surveyor"},
    {"key": "builder", "query": "Builder"},
    {"key": "building_materials", "query": "Building materials"},
    {"key": "lumber_store", "query": "Lumber store"},
    {"key": "hardware_store", "query": "Hardware store"},
    {"key": "paint_shop", "query": "Paint store"},
    {"key": "flooring_store", "query": "Flooring store"},
    {"key": "carpet_store", "query": "Carpet store"},
    {"key": "tile_store", "query": "Tile store"},
    {"key": "roofing_contractor", "query": "Roofing contractor"},
    {"key": "siding_contractor", "query": "Siding contractor"},
    {"key": "gutter_service", "query": "Gutter service"},
    {"key": "insulation_contractor", "query": "Insulation contractor"},
    {"key": "windows_installer", "query": "Window installation"},
    {"key": "fence_contractor", "query": "Fence contractor"},
    {"key": "garage_door_service", "query": "Garage door service"},
    {"key": "demolition_contractor", "query": "Demolition contractor"},
    {"key": "excavation_contractor", "query": "Excavation contractor"},
    {"key": "concrete_contractor", "query": "Concrete contractor"},
    {"key": "masonry_contractor", "query": "Masonry contractor"},
    {"key": "plumber", "query": "Plumber"},
    {"key": "electrician", "query": "Electrician"},
    {"key": "hvac", "query": "HVAC contractor"},
    {"key": "heating_contractor", "query": "Heating contractor"},
    {"key": "air_conditioning", "query": "Air conditioning service"},
    {"key": "moving_company", "query": "Moving company"},
    {"key": "storage_facility", "query": "Self storage"},
    {"key": "junk_removal", "query": "Junk removal service"},
    {"key": "dumpster_rental", "query": "Dumpster rental"},
    {"key": "landscaper", "query": "Landscaper"},
    {"key": "lawn_care", "query": "Lawn care service"},
    {"key": "tree_service", "query": "Tree service"},
    {"key": "pest_control", "query": "Pest control"},
    {"key": "termite_control", "query": "Termite control"},
    {"key": "pool_cleaner", "query": "Pool cleaner"},
    {"key": "pool_maintenance", "query": "Pool maintenance"},

    # --- Trading, Retail & Wholesale ---
    {"key": "trading_company", "query": "Trading company"},
    {"key": "wholesale_supplier", "query": "Wholesale supplier"},
    {"key": "distribution_company", "query": "Distribution company"},
    {"key": "exporter", "query": "Exporter"},
    {"key": "importer", "query": "Importer"},
    {"key": "supermarket", "query": "Supermarket"},
    {"key": "hypermarket", "query": "Hypermarket"},
    {"key": "department_store", "query": "Department store"},
    {"key": "grocery_store", "query": "Grocery store"},
    {"key": "organic_food_store", "query": "Organic food store"},
    {"key": "convenience_store", "query": "Convenience store"},
    {"key": "retail_shop", "query": "Retail store"},
    {"key": "shopping_mall", "query": "Shopping mall"},
    {"key": "outlet_store", "query": "Outlet store"},
    {"key": "discount_store", "query": "Discount store"},
    {"key": "thrift_store", "query": "Thrift store"},
    {"key": "consignment_store", "query": "Consignment store"},
    {"key": "furniture_store", "query": "Furniture store"},
    {"key": "home_furnishing", "query": "Home furnishing store"},
    {"key": "home_improvement", "query": "Home improvement store"},
    {"key": "home_appliance", "query": "Appliance store"},
    {"key": "electronics_store", "query": "Electronics store"},
    {"key": "computer_repair", "query": "Computer repair service"},
    {"key": "mobile_phone_shop", "query": "Cell phone store"},
    {"key": "phone_repair", "query": "Phone repair shop"},
    {"key": "computer_shop", "query": "Computer store"},
    {"key": "clothing_store", "query": "Clothing store"},
    {"key": "mens_clothing", "query": "Men's clothing store"},
    {"key": "womens_clothing", "query": "Women's clothing store"},
    {"key": "childrens_clothing", "query": "Children's clothing store"},
    {"key": "baby_store", "query": "Baby store"},
    {"key": "maternity_store", "query": "Maternity store"},
    {"key": "bridal_shop", "query": "Bridal shop"},
    {"key": "tuxedo_shop", "query": "Tuxedo shop"},
    {"key": "shoe_store", "query": "Shoe store"},
    {"key": "bag_shop", "query": "Bag shop"},
    {"key": "luggage_store", "query": "Luggage store"},
    {"key": "jewelry_shop", "query": "Jewelry store"},
    {"key": "watch_repair", "query": "Watch repair shop"},
    {"key": "cosmetics_store", "query": "Cosmetics store"},
    {"key": "perfume_store", "query": "Perfume store"},
    {"key": "book_store", "query": "Bookstore"},
    {"key": "stationery_store", "query": "Stationery store"},
    {"key": "comic_store", "query": "Comic book store"},
    {"key": "toy_store", "query": "Toy store"},
    {"key": "game_store", "query": "Video game store"},
    {"key": "hobby_shop", "query": "Hobby shop"},
    {"key": "sports_goods", "query": "Sporting goods store"},
    {"key": "outdoor_store", "query": "Outdoor gear store"},
    {"key": "bicycle_shop", "query": "Bicycle shop"},
    {"key": "music_store", "query": "Musical instrument store"},
    {"key": "optical_store", "query": "Eyewear store"},
    {"key": "gift_shop", "query": "Gift shop"},
    {"key": "card_shop", "query": "Card shop"},
    {"key": "party_supply", "query": "Party supplies"},
    {"key": "flower_shop", "query": "Florist"},
    {"key": "chocolate_shop", "query": "Chocolate shop"},
    {"key": "ice_cream_parlor", "query": "Ice cream shop"},
    {"key": "bakery", "query": "Bakery"},
    {"key": "cake_shop", "query": "Cake shop"},
    {"key": "donut_shop", "query": "Donut shop"},
    {"key": "coffee_shop", "query": "Coffee shop"},
    {"key": "tea_house", "query": "Tea house"},
    {"key": "juice_bar", "query": "Juice bar"},
    {"key": "wine_shop", "query": "Wine shop"},
    {"key": "liquor_store", "query": "Liquor store"},
    {"key": "beer_store", "query": "Beer store"},
    {"key": "cigar_shop", "query": "Cigar shop"},
    {"key": "vape_shop", "query": "Vape shop"},
    {"key": "tobacco_shop", "query": "Tobacco shop"},
    {"key": "antique_store", "query": "Antique store"},
    {"key": "art_gallery", "query": "Art gallery"},
    {"key": "craft_store", "query": "Craft store"},
    {"key": "fabric_store", "query": "Fabric store"},
    {"key": "yarn_store", "query": "Yarn store"},
    {"key": "sewing_shop", "query": "Sewing shop"},

    # --- Professional Services ---
    {"key": "business_consultancy", "query": "Business consultant"},
    {"key": "management_consulting", "query": "Management consultant"},
    {"key": "marketing_agency", "query": "Marketing agency"},
    {"key": "advertising_agency", "query": "Advertising agency"},
    {"key": "digital_marketing", "query": "Digital marketing agency"},
    {"key": "pr_firm", "query": "Public relations firm"},
    {"key": "seo_agency", "query": "SEO agency"},
    {"key": "branding_agency", "query": "Branding agency"},
    {"key": "market_research", "query": "Market research company"},
    {"key": "call_center", "query": "Call center"},
    {"key": "bpo", "query": "BPO company"},
    {"key": "answering_service", "query": "Answering service"},
    {"key": "it_services", "query": "IT support"},
    {"key": "software_company", "query": "Software company"},
    {"key": "app_developer", "query": "App developer"},
    {"key": "web_development", "query": "Web design company"},
    {"key": "data_center", "query": "Data center"},
    {"key": "cloud_services", "query": "Cloud services"},
    {"key": "cyber_security", "query": "Cybersecurity company"},
    {"key": "media_company", "query": "Media company"},
    {"key": "production_house", "query": "Production company"},
    {"key": "news_agency", "query": "News service"},
    {"key": "publishing_company", "query": "Publisher"},
    {"key": "printing_press", "query": "Print shop"},
    {"key": "sign_maker", "query": "Sign company"},
    {"key": "event_management", "query": "Event planner"},
    {"key": "wedding_planner", "query": "Wedding planner"},
    {"key": "party_planner", "query": "Party planner"},
    {"key": "catering_service", "query": "Caterer"},
    {"key": "dj_service", "query": "DJ service"},
    {"key": "entertainment_agency", "query": "Entertainment agency"},
    {"key": "law_firm", "query": "Law firm"},
    {"key": "lawyer", "query": "Lawyer"},
    {"key": "legal_services", "query": "Legal services"},
    {"key": "notary_public", "query": "Notary"},
    {"key": "paralegal", "query": "Paralegal service"},
    {"key": "mediation_service", "query": "Mediation service"},
    {"key": "audit_firm", "query": "Accounting firm"},
    {"key": "accounting", "query": "Accountant"},
    {"key": "bookkeeping", "query": "Bookkeeper"},
    {"key": "tax_consultant", "query": "Tax consultant"},
    {"key": "payroll_service", "query": "Payroll service"},
    {"key": "employment_agency", "query": "Employment agency"},
    {"key": "recruiter", "query": "Recruiter"},
    {"key": "headhunter", "query": "Executive search firm"},
    {"key": "career_coach", "query": "Career coach"},
    {"key": "translation_service", "query": "Translation service"},
    {"key": "interpretation_service", "query": "Interpretation service"},
    {"key": "private_investigator", "query": "Private investigator"},
    {"key": "detective_agency", "query": "Detective agency"},
    {"key": "background_check", "query": "Background check service"},
    {"key": "research_institute", "query": "Research institute"},
    {"key": "think_tank", "query": "Think tank"},

    # --- Finance & Insurance ---
    {"key": "bank", "query": "Bank"},
    {"key": "credit_union", "query": "Credit union"},
    {"key": "atm", "query": "ATM"},
    {"key": "insurance_company", "query": "Insurance agency"},
    {"key": "insurance_broker", "query": "Insurance broker"},
    {"key": "insurance_agent", "query": "Insurance agent"},
    {"key": "life_insurance", "query": "Life insurance agency"},
    {"key": "health_insurance", "query": "Health insurance agency"},
    {"key": "car_insurance", "query": "Auto insurance agency"},
    {"key": "home_insurance", "query": "Home insurance agency"},
    {"key": "finance_company", "query": "Finance company"},
    {"key": "investment_company", "query": "Investment firm"},
    {"key": "stock_broker", "query": "Stockbroker"},
    {"key": "financial_advisor", "query": "Financial planner"},
    {"key": "wealth_management", "query": "Wealth manager"},
    {"key": "microfinance", "query": "Microfinance institution"},
    {"key": "cooperative_bank", "query": "Cooperative bank"},
    {"key": "money_transfer", "query": "Money transfer service"},
    {"key": "currency_exchange", "query": "Currency exchange"},
    {"key": "check_cashing", "query": "Check cashing service"},
    {"key": "pawn_shop", "query": "Pawn shop"},
    {"key": "loan_agency", "query": "Loan company"},
    {"key": "mortgage_broker", "query": "Mortgage broker"},
    {"key": "debt_relief", "query": "Debt relief agency"},
    {"key": "credit_counseling", "query": "Credit counseling service"},
    {"key": "accountant", "query": "CPA"},
    {"key": "tax_preparer", "query": "Tax preparer"},

    # --- Logistics, Transport & Warehousing ---
    {"key": "logistics_company", "query": "Logistics provider"},
    {"key": "supply_chain", "query": "Supply chain management"},
    {"key": "transport_company", "query": "Transportation service"},
    {"key": "trucking_company", "query": "Trucking company"},
    {"key": "courier_service", "query": "Courier service"},
    {"key": "delivery_service", "query": "Delivery service"},
    {"key": "cargo_service", "query": "Cargo agent"},
    {"key": "freight_forwarding", "query": "Freight forwarder"},
    {"key": "shipping_company", "query": "Shipping company"},
    {"key": "warehouse", "query": "Warehouse"},
    {"key": "cold_storage", "query": "Cold storage"},
    {"key": "fulfillment_center", "query": "Fulfillment center"},
    {"key": "distribution_center", "query": "Distribution center"},
    {"key": "customs_broker", "query": "Customs broker"},
    {"key": "import_export", "query": "Import-export business"},
    {"key": "packaging_service", "query": "Packing service"},
    {"key": "crane_service", "query": "Crane service"},
    {"key": "forklift_dealer", "query": "Forklift dealer"},
    {"key": "port_authority", "query": "Port"},

    # --- Travel, Tourism & Hospitality ---
    {"key": "travel_agency", "query": "Travel agency"},
    {"key": "tour_operator", "query": "Tour operator"},
    {"key": "tourism_info", "query": "Tourist information"},
    {"key": "trekking_agency", "query": "Trekking agency"},
    {"key": "adventure_sport", "query": "Adventure sports"},
    {"key": "hotel", "query": "Hotel"},
    {"key": "motel", "query": "Motel"},
    {"key": "resort", "query": "Resort"},
    {"key": "lodge", "query": "Lodge"},
    {"key": "inn", "query": "Inn"},
    {"key": "guest_house", "query": "Guest house"},
    {"key": "hostel", "query": "Hostel"},
    {"key": "backpackers", "query": "Backpacker hostel"},
    {"key": "homestay", "query": "Homestay"},
    {"key": "bed_and_breakfast", "query": "Bed and breakfast"},
    {"key": "timeshare", "query": "Timeshare"},
    {"key": "vacation_rental", "query": "Vacation rental"},
    {"key": "campground", "query": "Campground"},
    {"key": "rv_park", "query": "RV park"},
    {"key": "restaurant", "query": "Restaurant"},
    {"key": "fine_dining", "query": "Fine dining restaurant"},
    {"key": "family_restaurant", "query": "Family restaurant"},
    {"key": "cafe", "query": "Cafe"},
    {"key": "coffee_shop", "query": "Coffee shop"},
    {"key": "tea_house", "query": "Tea room"},
    {"key": "bakery", "query": "Bakery"},
    {"key": "fast_food", "query": "Fast food restaurant"},
    {"key": "hamburger_restaurant", "query": "Burger restaurant"},
    {"key": "pizza_restaurant", "query": "Pizza restaurant"},
    {"key": "sushi_restaurant", "query": "Sushi restaurant"},
    {"key": "chinese_restaurant", "query": "Chinese restaurant"},
    {"key": "japanese_restaurant", "query": "Japanese restaurant"},
    {"key": "indian_restaurant", "query": "Indian restaurant"},
    {"key": "italian_restaurant", "query": "Italian restaurant"},
    {"key": "mexican_restaurant", "query": "Mexican restaurant"},
    {"key": "thai_restaurant", "query": "Thai restaurant"},
    {"key": "korean_restaurant", "query": "Korean restaurant"},
    {"key": "mediterranean_restaurant", "query": "Mediterranean restaurant"},
    {"key": "greek_restaurant", "query": "Greek restaurant"},
    {"key": "french_restaurant", "query": "French restaurant"},
    {"key": "lebanese_restaurant", "query": "Lebanese restaurant"},
    {"key": "vietnamese_restaurant", "query": "Vietnamese restaurant"},
    {"key": "spanish_restaurant", "query": "Spanish restaurant"},
    {"key": "steakhouse", "query": "Steakhouse"},
    {"key": "seafood_restaurant", "query": "Seafood restaurant"},
    {"key": "bbq_joint", "query": "BBQ restaurant"},
    {"key": "deli", "query": "Deli"},
    {"key": "sandwich_shop", "query": "Sandwich shop"},
    {"key": "breakfast_restaurant", "query": "Breakfast restaurant"},
    {"key": "brunch_restaurant", "query": "Brunch restaurant"},
    {"key": "vegetarian_restaurant", "query": "Vegetarian restaurant"},
    {"key": "vegan_restaurant", "query": "Vegan restaurant"},
    {"key": "gluten_free_restaurant", "query": "Gluten-free restaurant"},
    {"key": "organic_restaurant", "query": "Organic restaurant"},
    {"key": "food_truck", "query": "Food truck"},
    {"key": "food_stand", "query": "Food stand"},
    {"key": "hot_dog_stand", "query": "Hot dog stand"},
    {"key": "ice_cream_shop", "query": "Ice cream shop"},
    {"key": "juice_bar", "query": "Juice bar"},
    {"key": "smoothie_shop", "query": "Smoothie shop"},
    {"key": "bar_pub", "query": "Bar"},
    {"key": "sports_bar", "query": "Sports bar"},
    {"key": "karaoke_bar", "query": "Karaoke bar"},
    {"key": "wine_bar", "query": "Wine bar"},
    {"key": "brewery", "query": "Brewery"},
    {"key": "distillery", "query": "Distillery"},
    {"key": "nightclub", "query": "Nightclub"},
    {"key": "strip_club", "query": "Gentlemen's club"},
    {"key": "sweet_shop", "query": "Candy store"},
    {"key": "catering_service", "query": "Caterer"},
    {"key": "event_venue", "query": "Event venue"},
    {"key": "conference_center", "query": "Conference center"},
    {"key": "banquet_hall", "query": "Banquet hall"},
    {"key": "meeting_room", "query": "Meeting room"},

    # --- Utilities & Services ---
    {"key": "telecom_company", "query": "Telecommunications"},
    {"key": "internet_service_provider", "query": "Internet service provider"},
    {"key": "isp", "query": "ISP"},
    {"key": "cable_provider", "query": "Cable company"},
    {"key": "satellite_provider", "query": "Satellite TV provider"},
    {"key": "electricity_provider", "query": "Electric utility"},
    {"key": "power_plant", "query": "Power plant"},
    {"key": "water_supplier", "query": "Water utility"},
    {"key": "waste_management", "query": "Waste management"},
    {"key": "recycling_center", "query": "Recycling center"},
    {"key": "dump", "query": "Landfill"},
    {"key": "sanitation_service", "query": "Sanitation"},
    {"key": "septic_services", "query": "Septic system service"},
    {"key": "cleaning_services", "query": "Cleaning service"},
    {"key": "commercial_cleaning", "query": "Commercial cleaning"},
    {"key": "janitorial_service", "query": "Janitorial service"},
    {"key": "maid_service", "query": "Maid service"},
    {"key": "carpet_cleaning", "query": "Carpet cleaner"},
    {"key": "upholstery_cleaning", "query": "Upholstery cleaning"},
    {"key": "pressure_washing", "query": "Pressure washing service"},
    {"key": "window_cleaning", "query": "Window cleaner"},
    {"key": "chimney_sweep", "query": "Chimney sweep"},
    {"key": "pest_control", "query": "Exterminator"},
    {"key": "termite_control", "query": "Termite control"},
    {"key": "animal_control", "query": "Animal control service"},
    {"key": "security_services", "query": "Security service"},
    {"key": "security_guard", "query": "Security guard"},
    {"key": "private_security", "query": "Private investigation"},
    {"key": "fire_alarm", "query": "Fire protection"},
    {"key": "cctv_installation", "query": "Security system installer"},
    {"key": "locksmith", "query": "Locksmith"},
    {"key": "laundry_services", "query": "Laundry service"},
    {"key": "dry_cleaners", "query": "Dry cleaner"},
    {"key": "laundromat", "query": "Laundromat"},
    {"key": "tailor", "query": "Tailor"},
    {"key": "alterations", "query": "Clothing alterations"},
    {"key": "shoe_repair", "query": "Shoe repair"},
    {"key": "key_duplication", "query": "Key cutter"},
    {"key": "photography_studio", "query": "Photography studio"},
    {"key": "photographer", "query": "Photographer"},
    {"key": "videographer", "query": "Videographer"},
    {"key": "florist", "query": "Florist"},
    {"key": "gift_shop", "query": "Gift shop"},

    # --- Arts, Culture & Entertainment ---
    {"key": "movie_theater", "query": "Movie theater"},
    {"key": "cinema", "query": "Cinema"},
    {"key": "drive_in_theater", "query": "Drive-in theater"},
    {"key": "art_gallery", "query": "Art gallery"},
    {"key": "museum", "query": "Museum"},
    {"key": "history_museum", "query": "History museum"},
    {"key": "science_museum", "query": "Science museum"},
    {"key": "art_museum", "query": "Art museum"},
    {"key": "library", "query": "Library"},
    {"key": "auditorium", "query": "Auditorium"},
    {"key": "theater", "query": "Performing arts theater"},
    {"key": "concert_hall", "query": "Concert hall"},
    {"key": "opera_house", "query": "Opera house"},
    {"key": "cultural_center", "query": "Cultural center"},
    {"key": "community_center", "query": "Community center"},
    {"key": "youth_center", "query": "Youth center"},
    {"key": "senior_center", "query": "Senior center"},
    {"key": "nightclub", "query": "Nightclub"},
    {"key": "comedy_club", "query": "Comedy club"},
    {"key": "jazz_club", "query": "Jazz club"},
    {"key": "casino", "query": "Casino"},
    {"key": "gambling_house", "query": "Gambling house"},
    {"key": "amusement_park", "query": "Amusement park"},
    {"key": "theme_park", "query": "Theme park"},
    {"key": "water_park", "query": "Water park"},
    {"key": "zoo", "query": "Zoo"},
    {"key": "aquarium", "query": "Aquarium"},
    {"key": "botanical_garden", "query": "Botanical garden"},
    {"key": "planetarium", "query": "Planetarium"},
    {"key": "observatory", "query": "Observatory"},

    # --- Public & Government ---
    {"key": "city_hall", "query": "City hall"},
    {"key": "courthouse", "query": "Courthouse"},
    {"key": "police_station", "query": "Police station"},
    {"key": "fire_station", "query": "Fire station"},
    {"key": "post_office", "query": "Post office"},
    {"key": "embassy", "query": "Embassy"},
    {"key": "consulate", "query": "Consulate"},
    {"key": "government_office", "query": "Government office"},
    {"key": "public_works", "query": "Public works"},
    {"key": "dmv", "query": "DMV"},
    {"key": "tax_office", "query": "Tax office"},
    {"key": "unemployment_office", "query": "Unemployment office"},
    {"key": "social_security", "query": "Social security office"},
    {"key": "military_base", "query": "Military base"},
    {"key": "recruiting_station", "query": "Military recruiting station"},
    {"key": "immigration_office", "query": "Immigration office"},
    {"key": "passport_office", "query": "Passport office"},
    {"key": "veterans_affairs", "query": "Veterans affairs office"},

    # --- Sports & Recreation ---
    {"key": "stadium", "query": "Stadium"},
    {"key": "arena", "query": "Arena"},
    {"key": "golf_course", "query": "Golf course"},
    {"key": "golf_club", "query": "Golf club"},
    {"key": "tennis_court", "query": "Tennis court"},
    {"key": "tennis_club", "query": "Tennis club"},
    {"key": "swimming_pool", "query": "Swimming pool"},
    {"key": "public_pool", "query": "Public pool"},
    {"key": "bowling_alley", "query": "Bowling alley"},
    {"key": "skating_rink", "query": "Ice skating rink"},
    {"key": "roller_skating", "query": "Roller skating rink"},
    {"key": "ski_area", "query": "Ski area"},
    {"key": "hiking_area", "query": "Hiking trail"},
    {"key": "campground", "query": "Campsite"},
    {"key": "rv_park", "query": "RV park"},
    {"key": "marina", "query": "Marina"},
    {"key": "fishing_charter", "query": "Fishing charter"},
    {"key": "boat_rental", "query": "Boat rental"},
    {"key": "kayak_rental", "query": "Kayak rental"},
    {"key": "surf_shop", "query": "Surf shop"},
    {"key": "dive_shop", "query": "Dive shop"},
    {"key": "sports_complex", "query": "Sports complex"},
    {"key": "playground", "query": "Playground"},
    {"key": "park", "query": "Park"},
    {"key": "national_park", "query": "National park"},
    {"key": "state_park", "query": "State park"},
    {"key": "beach", "query": "Beach"},
    {"key": "gun_range", "query": "Shooting range"},
    {"key": "archery_range", "query": "Archery range"},
    {"key": "paintball_field", "query": "Paintball center"},
    {"key": "go_kart_track", "query": "Go-kart track"},
    {"key": "miniature_golf", "query": "Miniature golf"},

    # --- Religious Organizations ---
    {"key": "church", "query": "Church"},
    {"key": "cathedral", "query": "Cathedral"},
    {"key": "mosque", "query": "Mosque"},
    {"key": "hindu_temple", "query": "Hindu temple"},
    {"key": "buddhist_temple", "query": "Buddhist temple"},
    {"key": "synagogue", "query": "Synagogue"},
    {"key": "gurdwara", "query": "Gurdwara"},
    {"key": "monastery", "query": "Monastery"},
    {"key": "convent", "query": "Convent"},
    {"key": "shrine", "query": "Shrine"},
    {"key": "religious_organization", "query": "Religious organization"},
    {"key": "seminary", "query": "Seminary"},

    # --- Funeral & Cemeteries ---
    {"key": "funeral_home", "query": "Funeral home"},
    {"key": "mortuary", "query": "Mortuary"},
    {"key": "crematorium", "query": "Crematory"},
    {"key": "cemetery", "query": "Cemetery"},
    {"key": "memorial_park", "query": "Memorial park"},
    {"key": "mausoleum", "query": "Mausoleum"},
    {"key": "columbarium", "query": "Columbarium"},
    
    # --- Additional Niche & Specialized Industries (Expanded) ---
    {"key": "aquarium_store", "query": "Aquarium store"},
    {"key": "mattress_store", "query": "Mattress store"},
    {"key": "vacuum_cleaner_store", "query": "Vacuum cleaner store"},
    {"key": "wigs_shop", "query": "Wigs shop"},
    {"key": "hearing_aid_store", "query": "Hearing aid store"},
    {"key": "clock_repair", "query": "Clock repair"},
    {"key": "shoe_shine", "query": "Shoe shine"},
    {"key": "window_tinting", "query": "Window tinting"},
    {"key": "rv_repair", "query": "RV repair"},
    {"key": "smog_check_station", "query": "Smog check station"},
    {"key": "car_stereo_installation", "query": "Car stereo installation"},
    {"key": "paintless_dent_repair", "query": "Paintless dent repair"},
    {"key": "waterproofing", "query": "Waterproofing service"},
    {"key": "asbestos_removal", "query": "Asbestos removal service"},
    {"key": "asphalt_paving", "query": "Asphalt paving"},
    {"key": "septic_tank_pumping", "query": "Septic tank pumping"},
    {"key": "water_damage_restoration", "query": "Water damage restoration"},
    {"key": "mold_remediation", "query": "Mold remediation"},
    {"key": "deck_builder", "query": "Deck builder"},
    {"key": "fence_builder", "query": "Fence builder"},
    {"key": "sunroom_contractor", "query": "Sunroom contractor"},
    {"key": "basement_finishing", "query": "Basement finishing"},
    {"key": "graphic_designer", "query": "Graphic designer"},
    {"key": "video_production", "query": "Video production service"},
    {"key": "voice_over_artist", "query": "Voice over artist"},
    {"key": "secretarial_service", "query": "Secretarial service"},
    {"key": "virtual_office", "query": "Virtual office"},
    {"key": "business_incubator", "query": "Business incubator"},
    {"key": "sleep_clinic", "query": "Sleep clinic"},
    {"key": "allergist", "query": "Allergist"},
    {"key": "physiatrist", "query": "Physiatrist"},
    {"key": "occupational_therapist", "query": "Occupational therapist"},
    {"key": "speech_therapist", "query": "Speech therapist"},
    {"key": "doula", "query": "Doula"},
    {"key": "midwife", "query": "Midwife"},
    {"key": "frozen_yogurt_shop", "query": "Frozen yogurt shop"},
    {"key": "bubble_tea_shop", "query": "Bubble tea shop"},
    {"key": "creperie", "query": "Creperie"},
    {"key": "falafel_restaurant", "query": "Falafel restaurant"},
    {"key": "cafeteria", "query": "Cafeteria"},
    {"key": "coffee_roaster", "query": "Coffee roaster"},
    {"key": "tent_rental", "query": "Tent rental"},
    {"key": "party_equipment_rental", "query": "Party equipment rental"},
    {"key": "wedding_venue", "query": "Wedding venue"},
    {"key": "life_coach", "query": "Life coach"},
    {"key": "image_consultant", "query": "Image consultant"},
    {"key": "personal_shopper", "query": "Personal shopper"},
    {"key": "feng_shui_consultant", "query": "Feng shui consultant"},
    {"key": "astrologer", "query": "Astrologer"},
    {"key": "ngo", "query": "Non-profit organization"},
    {"key": "chamber_of_commerce", "query": "Chamber of commerce"},
    {"key": "association", "query": "Association"}
]

# -----------------------------
# ALL 77 DISTRICTS + Major Cities
# -----------------------------
districts = [
    "Kathmandu",
    "Lalitpur",  
    "Bhaktapur",
    "Biratnagar",
    "Dhangadhi",
    "Pokhara"
    
    
]
import os
import json

# Create output folder
output_folder = "nepal_search_config"
os.makedirs(output_folder, exist_ok=True)

for district in districts:
    district_slug = district.lower().replace(" ", "_")
    district_targets = []

    for industry in industries:
        district_targets.append({
            "room_id": f"b2b_target_nepal_{district_slug}",
            "query": f"{industry['query']} in",
            "location": f"{district}, Nepal",
            "zoom": 13
        })

    # ✅ Updated filename format
    filename = f"nepal_b2b_{district_slug}.json"

    with open(f"{output_folder}/{filename}", "w", encoding="utf-8") as f:
        json.dump(district_targets, f, indent=2, ensure_ascii=False)

print("✅ Nepal B2B district files generated inside 'nepal_search_config' folder.")

